version: '3.7'

services:
  app: 
    build:
      context: ./Sandwish.Server
      dockerfile: Dockerfile
    expose:
      - "5001"

  proxy: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app